const API='https://rey-ink-browser.vercel.app/api/rey-ink';let poller=false,autoTimer=null,pointer=null,offscreenCreating=null;const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function api(action,body={}){const r=await fetch(API,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action,...body}),cache:'no-store'});const d=await r.json().catch(()=>({error:'Respuesta inválida'}));if(!r.ok||d.ok===false)throw Error(d.error||`HTTP ${r.status}`);return d}
async function tab(){const s=await chrome.storage.local.get('reyInkControlledTabId');if(s.reyInkControlledTabId)try{const t=await chrome.tabs.get(Number(s.reyInkControlledTabId));if(t?.id&&/^https?:/i.test(t.url||''))return t}catch{}const a=await chrome.tabs.query({active:true,currentWindow:true}),t=a.find(x=>x?.id&&/^https?:/i.test(x.url||''));if(t?.id)await chrome.storage.local.set({reyInkControlledTabId:t.id});return t||null}
async function attach(id){try{await chrome.debugger.attach({tabId:id},'1.3')}catch(e){if(!/already attached/i.test(String(e?.message||e)))throw e}}
async function cdp(id,m,p={}){await attach(id);try{return await chrome.debugger.sendCommand({tabId:id},m,p)}catch(e){if(/detached|not attached|target closed/i.test(String(e?.message||e))){try{await chrome.debugger.detach({tabId:id})}catch{}await attach(id);return chrome.debugger.sendCommand({tabId:id},m,p)}throw e}}
async function vp(id){const x=await cdp(id,'Page.getLayoutMetrics'),v=x?.cssVisualViewport||x?.visualViewport||{};return{w:Number(v.clientWidth||v.width)||1280,h:Number(v.clientHeight||v.height)||720}}
async function prep(id){await cdp(id,'Page.enable');await cdp(id,'Runtime.enable');await cdp(id,'Input.setIgnoreInputEvents',{ignore:false})}
async function mouse(id,type,p){await prep(id);return cdp(id,'Input.dispatchMouseEvent',{type,...p})}
async function click(id,x,y,b='left',n=1){await mouse(id,'mouseMoved',{x,y,button:'none',buttons:0,pointerType:'mouse'});const q=b==='left'?1:b==='right'?2:4;await mouse(id,'mousePressed',{x,y,button:b,buttons:q,clickCount:n,pointerType:'mouse'});await mouse(id,'mouseReleased',{x,y,button:b,buttons:0,clickCount:n,pointerType:'mouse'})}
async function typeText(id,text){await prep(id);await cdp(id,'Input.insertText',{text:String(text||'')})}
async function key(id,p){await prep(id);const key=String(p.key||'Enter'),code=String(p.code||key),text=String(p.text||'');await cdp(id,'Input.dispatchKeyEvent',{type:'keyDown',key,code,text,unmodifiedText:text});await cdp(id,'Input.dispatchKeyEvent',{type:'keyUp',key,code})}
async function ensureOff(){const u=chrome.runtime.getURL('offscreen.html'),c=await chrome.runtime.getContexts({contextTypes:['OFFSCREEN_DOCUMENT'],documentUrls:[u]});if(c.length)return;if(offscreenCreating){await offscreenCreating;return}offscreenCreating=chrome.offscreen.createDocument({url:'offscreen.html',reasons:['USER_MEDIA'],justification:'Canal WebRTC para el control remoto.'});try{await offscreenCreating}finally{offscreenCreating=null}}
async function off(m){await ensureOff();return new Promise(r=>chrome.runtime.sendMessage({...m,target:'offscreen'},x=>r(x||{ok:true})))}
async function register(){const s=await chrome.storage.local.get('reyInkPcSlot'),slot=Number(s.reyInkPcSlot);if(slot<1||slot>20)throw Error('Selecciona PC1–PC20.');const t=await tab(),old=(await chrome.storage.local.get('reyInkRemote')).reyInkRemote||{},token=old.token||crypto.randomUUID(),r=await api('register_device',{pc_slot:slot,token,state:{tabId:t?.id||null,url:t?.url||'',title:t?.title||''}});await chrome.storage.local.set({reyInkRemote:{enabled:true,token:r.token||token,pcSlot:slot,session:r.session_id},reyInkRelayStatus:{connected:true,lastConnected:Date.now()}});startPoll();return{ok:true}}
async function state(){const t=await tab(),s=await chrome.storage.local.get(['reyInkPcSlot','reyInkRemote','reyInkRelayStatus','reyInkAutoRoutines','reyInkAutoDraft','reyInkAutoSchedule']);return{ok:true,tabId:t?.id||null,url:t?.url||'',title:t?.title||'',pcSlot:s.reyInkPcSlot||null,remote:s.reyInkRemote||null,relayStatus:s.reyInkRelayStatus||null,routines:s.reyInkAutoRoutines||[],draft:s.reyInkAutoDraft||[],updateBot:s.reyInkAutoSchedule||{enabled:false}}}
async function command(c){const t=await tab(),id=t?.id;if(!id&&c.command!=='get_state')throw Error('No hay pestaña web controlada.');const p=c.payload||{};switch(c.command){case'get_state':return state();case'click':{const v=await vp(id);await click(id,Number(p.nx)*v.w,Number(p.ny)*v.h,p.button||'left',Number(p.clickCount)||1);return{ok:true}}case'scroll':{const v=await vp(id);await mouse(id,'mouseWheel',{x:Number(p.nx)*v.w,y:Number(p.ny)*v.h,deltaX:Number(p.dx)||0,deltaY:Number(p.dy)||0});return{ok:true}}case'type':await typeText(id,p.text);return{ok:true};case'key':await key(id,p);return{ok:true};case'back':await chrome.tabs.goBack(id);return{ok:true};case'forward':await chrome.tabs.goForward(id);return{ok:true};case'reload':await chrome.tabs.reload(id);return{ok:true};case'new_tab':{const n=await chrome.tabs.create({url:p.url||'https://www.google.com',active:true});await chrome.storage.local.set({reyInkControlledTabId:n.id});return{ok:true}}case'navigate':{let u=String(p.url||'').trim();if(!/^https?:/i.test(u))u='https://'+u;await chrome.tabs.update(id,{url:u,active:true});return{ok:true}}case'autoclick_start':{const v=await vp(id),x=Number(p.nx)*v.w,y=Number(p.ny)*v.h,ms=Math.max(100,Math.min(3600000,Number(p.interval)||960000));if(autoTimer)clearInterval(autoTimer);await click(id,x,y);autoTimer=setInterval(()=>click(id,x,y).catch(()=>{}),ms);return{ok:true}}case'autoclick_stop':if(autoTimer)clearInterval(autoTimer);autoTimer=null;return{ok:true};default:throw Error('Comando no reconocido: '+c.command)}}
async function remoteMouse(m){const t=await tab();if(!t?.id)throw Error('No hay pestaña controlada.');const v=await vp(t.id),x=Math.max(0,Math.min(v.w,Number(m.x)*v.w)),y=Math.max(0,Math.min(v.h,Number(m.y)*v.h));if(m.action==='down'){await mouse(t.id,'mouseMoved',{x,y,button:'none',buttons:0,pointerType:'mouse'});await mouse(t.id,'mousePressed',{x,y,button:m.button||'left',buttons:1,clickCount:1,pointerType:'mouse'});pointer={x,y,button:m.button||'left'};return{ok:true}}if(m.action==='move'&&pointer){await mouse(t.id,'mouseMoved',{x,y,button:pointer.button,buttons:1,pointerType:'mouse'});pointer.x=x;pointer.y=y;return{ok:true}}if(m.action==='up'&&pointer){await mouse(t.id,'mouseMoved',{x,y,button:pointer.button,buttons:1,pointerType:'mouse'});await mouse(t.id,'mouseReleased',{x,y,button:pointer.button,buttons:0,clickCount:1,pointerType:'mouse'});pointer=null;return{ok:true}}if(m.action==='wheel'){await mouse(t.id,'mouseWheel',{x,y,deltaX:Number(m.dx)||0,deltaY:Number(m.dy)||0});return{ok:true}}return{ok:false}}
async function poll(){const s=(await chrome.storage.local.get('reyInkRemote')).reyInkRemote;if(!s?.enabled)return;try{const d=await api('poll_command',{pc_slot:s.pcSlot,token:s.token});if(d.command){const result=await command(d.command).catch(e=>({ok:false,error:String(e?.message||e)}));await api('command_result',{pc_slot:s.pcSlot,token:s.token,command_id:d.command.id,result}).catch(()=>{})}}catch{}}
async function startPoll(){if(poller)return;poller=true;while(poller){await poll();await sleep(250)}poller=false}
async function saveRoutine(name){const s=await chrome.storage.local.get(['reyInkAutoDraft','reyInkAutoRoutines']),list=s.reyInkAutoRoutines||[];list.push({name:String(name||'Auto clic'),actions:s.reyInkAutoDraft||[],createdAt:Date.now()});await chrome.storage.local.set({reyInkAutoRoutines:list,reyInkAutoDraft:[]});return{ok:true,routines:list}}
async function handle(m){switch(m.type){case'SET_PC_SLOT':await chrome.storage.local.set({reyInkPcSlot:Number(m.pcSlot)});return{ok:true};case'REGISTER_REMOTE':return register();case'START_REMOTE_VIDEO':{const t=await tab();if(!t?.id)throw Error('No hay pestaña web.');await cdp(t.id,'Page.startScreencast',{format:'jpeg',quality:55,maxWidth:1280,maxHeight:720,everyNthFrame:1,sendLastFrame:true});return{ok:true}}case'STOP_REMOTE_VIDEO':{const t=await tab();if(t?.id)await cdp(t.id,'Page.stopScreencast').catch(()=>{});return{ok:true}}case'DISCONNECT_REMOTE':{poller=false;await chrome.alarms.clear('reyink-autoclick');if(autoTimer)clearInterval(autoTimer);autoTimer=null;try{const t=await tab();if(t?.id)await cdp(t.id,'Page.stopScreencast').catch(()=>{});if(t?.id)await chrome.debugger.detach({tabId:t.id})}catch{}await off({action:'WEBRTC_STOP'});await chrome.storage.local.set({reyInkRemote:{enabled:false},reyInkRelayStatus:{connected:false}});return{ok:true}}case'GET_STATE':return state();case'WEBRTC_HOST':return off({action:'WEBRTC_HOST'});case'WEBRTC_STOP':return off({action:'WEBRTC_STOP'});case'RELOAD':return command({command:'reload'});case'GO_BACK':return command({command:'back'});case'GO_FORWARD':return command({command:'forward'});case'NAVIGATE':return command({command:'navigate',payload:{url:m.url}});case'NEW_TAB':return command({command:'new_tab'});case'AUTO_RECORD_START':{const t=await tab();if(!t?.id)throw Error('Abre una página web primero.');await chrome.scripting.executeScript({target:{tabId:t.id},files:['content.js']}).catch(()=>{});await chrome.tabs.sendMessage(t.id,{type:'AUTO_RECORD_START'}).catch(()=>{});await chrome.storage.local.set({reyInkAutoDraft:[]});return{ok:true}}case'AUTO_RECORD_STOP':{const t=await tab();if(t?.id)await chrome.tabs.sendMessage(t.id,{type:'AUTO_RECORD_STOP'}).catch(()=>{});return{ok:true}}case'SAVE_AUTO_ROUTINE':return saveRoutine(m.name);case'SCHEDULE_AUTO':{const n=Math.max(.5,Number(m.minutes)||16);await chrome.alarms.clear('reyink-autoclick');await chrome.alarms.create('reyink-autoclick',{delayInMinutes:n,periodInMinutes:n});await chrome.storage.local.set({reyInkAutoSchedule:{enabled:true,index:Number(m.index),minutes:n}});return{ok:true}}case'STOP_SCHEDULE':await chrome.alarms.clear('reyink-autoclick');await chrome.storage.local.set({reyInkAutoSchedule:{enabled:false}});return{ok:true};case'RUN_ROUTINE_NOW':{const s=await chrome.storage.local.get('reyInkAutoRoutines'),row=(s.reyInkAutoRoutines||[])[Number(m.index)],t=await tab();if(!row?.actions?.length||!t?.id)throw Error('Rutina vacía.');const v=await vp(t.id);for(const a of row.actions){await click(t.id,Number(a.x)*v.w,Number(a.y)*v.h);await sleep(Number(a.delayMs)||250)}return{ok:true}}case'mouse':return remoteMouse(m);case'type':await typeText((await tab()).id,m.text);return{ok:true};case'key':await key((await tab()).id,m);return{ok:true};default:return{ok:false,error:'Comando no reconocido: '+m.type}}}
chrome.debugger.onEvent.addListener((src,method,p)=>{if(method==='Page.screencastFrame'&&src.tabId){off({action:'FRAME',data:p.data,meta:p.metadata,sessionId:p.sessionId}).catch(()=>{});chrome.debugger.sendCommand({tabId:src.tabId},'Page.screencastFrameAck',{sessionId:p.sessionId}).catch(()=>{})}});
chrome.runtime.onMessage.addListener((m,s,sendResponse)=>{handle(m).then(sendResponse).catch(e=>sendResponse({ok:false,error:String(e?.message||e)}));return true});
chrome.runtime.onMessage.addListener(m=>{if(m.type==='AUTO_CLICK_RECORDED')chrome.storage.local.get('reyInkAutoDraft').then(s=>{const a=s.reyInkAutoDraft||[];a.push({x:Number(m.x),y:Number(m.y),delayMs:250,url:m.url||'',title:m.title||''});return chrome.storage.local.set({reyInkAutoDraft:a})})});
chrome.alarms.onAlarm.addListener(async a=>{if(a.name!=='reyink-autoclick')return;const s=await chrome.storage.local.get('reyInkAutoSchedule');if(!s.reyInkAutoSchedule?.enabled)return;const r=await chrome.storage.local.get('reyInkAutoRoutines'),row=(r.reyInkAutoRoutines||[])[Number(s.reyInkAutoSchedule.index)],t=await tab();if(!row?.actions?.length||!t?.id)return;try{const v=await vp(t.id);for(const x of row.actions){await click(t.id,Number(x.x)*v.w,Number(x.y)*v.h);await sleep(Number(x.delayMs)||250)}}catch{}});
