const API='https://rey-ink-browser.vercel.app/api/rey-ink';
let polling=false,offscreenCreating=null;
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function api(action,body={}){const r=await fetch(API,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action,...body}),cache:'no-store'});const d=await r.json().catch(()=>({error:'Respuesta inválida'}));if(!r.ok||d.ok===false)throw Error(d.error||`HTTP ${r.status}`);return d}
async function tab(){const s=await chrome.storage.local.get('reyInkControlledTabId');if(s.reyInkControlledTabId)try{const t=await chrome.tabs.get(Number(s.reyInkControlledTabId));if(t?.id&&/^https?:/i.test(t.url||''))return t}catch{}const a=await chrome.tabs.query({active:true,currentWindow:true}),t=a.find(x=>x?.id&&/^https?:/i.test(x.url||''));if(t?.id)await chrome.storage.local.set({reyInkControlledTabId:t.id});return t||null}
async function attach(id){try{await chrome.debugger.attach({tabId:id},'1.3')}catch(e){if(!/already attached/i.test(String(e?.message||e)))throw e}}
async function cdp(id,m,p={}){await attach(id);try{return await chrome.debugger.sendCommand({tabId:id},m,p)}catch(e){if(/detached|not attached|target closed/i.test(String(e?.message||e))){try{await chrome.debugger.detach({tabId:id})}catch{}await attach(id);return chrome.debugger.sendCommand({tabId:id},m,p)}throw e}}
async function vp(id){const x=await cdp(id,'Page.getLayoutMetrics'),v=x?.cssVisualViewport||x?.visualViewport||{};return{w:Number(v.clientWidth||v.width)||1280,h:Number(v.clientHeight||v.height)||720}}
async function click(id,x,y,b='left',n=1){const q=b==='left'?1:b==='right'?2:4;await cdp(id,'Input.dispatchMouseEvent',{type:'mouseMoved',x,y,button:'none',buttons:0,pointerType:'mouse'});await cdp(id,'Input.dispatchMouseEvent',{type:'mousePressed',x,y,button:b,buttons:q,clickCount:n,pointerType:'mouse'});await cdp(id,'Input.dispatchMouseEvent',{type:'mouseReleased',x,y,button:b,buttons:0,clickCount:n,pointerType:'mouse'})}
async function prepare(id){await cdp(id,'Page.enable');await cdp(id,'Runtime.enable');await cdp(id,'Input.setIgnoreInputEvents',{ignore:false})}
async function execute(c){const t=await tab(),id=t?.id,p=c.payload||{};if(c.command!=='get_state'&&!id)throw Error('No hay pestaña controlada.');if(id)await chrome.storage.local.set({reyInkControlledTabId:id});switch(c.command){case'get_state':return{ok:true,tabId:id||null,url:t?.url||'',title:t?.title||''};case'click':{await prepare(id);const v=await vp(id);await click(id,Number(p.nx)*v.w,Number(p.ny)*v.h,p.button||'left',Number(p.clickCount)||1);return{ok:true}}case'double_click':{await prepare(id);const v=await vp(id);await click(id,Number(p.nx)*v.w,Number(p.ny)*v.h,'left',2);return{ok:true}}case'scroll':{await prepare(id);const v=await vp(id);await cdp(id,'Input.dispatchMouseEvent',{type:'mouseWheel',x:Number(p.nx)*v.w,y:Number(p.ny)*v.h,deltaX:Number(p.dx)||0,deltaY:Number(p.dy)||0});return{ok:true}}case'type':{await prepare(id);await cdp(id,'Input.insertText',{text:String(p.text||'')});return{ok:true}}case'key':{await prepare(id);const key=String(p.key||'Enter'),code=String(p.code||key),text=String(p.text||'');await cdp(id,'Input.dispatchKeyEvent',{type:'keyDown',key,code,text,unmodifiedText:text});await cdp(id,'Input.dispatchKeyEvent',{type:'keyUp',key,code});return{ok:true}}case'back':await chrome.tabs.goBack(id);return{ok:true};case'forward':await chrome.tabs.goForward(id);return{ok:true};case'reload':await chrome.tabs.reload(id);return{ok:true};case'navigate':{let u=String(p.url||'').trim();if(!/^https?:/i.test(u))u='https://'+u;await chrome.tabs.update(id,{url:u,active:true});return{ok:true,url:u}}default:throw Error('Comando no reconocido: '+c.command)}}
async function register(){const s=await chrome.storage.local.get('reyInkRemote'),pcSlot=Number(s.reyInkRemote?.pcSlot||1),t=await tab(),token=s.reyInkRemote?.token||crypto.randomUUID(),r=await api('register_device',{pc_slot:pcSlot,token,state:{tabId:t?.id||null,url:t?.url||'',title:t?.title||''}});await chrome.storage.local.set({reyInkRemote:{enabled:true,token:r.token||token,pcSlot,session:r.session_id},reyInkRelayStatus:{connected:true,lastConnected:Date.now()}});startPolling();return{ok:true,pcSlot,session:r.session_id}}
async function heartbeat(){const s=(await chrome.storage.local.get('reyInkRemote')).reyInkRemote;if(!s?.enabled)return;try{const t=await tab();await api('heartbeat',{pc_slot:s.pcSlot,token:s.token,state:{tabId:t?.id||null,url:t?.url||'',title:t?.title||''}});await chrome.storage.local.set({reyInkRelayStatus:{connected:true,lastConnected:Date.now()}})}catch(e){await chrome.storage.local.set({reyInkRelayStatus:{connected:false,error:String(e?.message||e)}})}}
async function poll(){const s=(await chrome.storage.local.get('reyInkRemote')).reyInkRemote;if(!s?.enabled)return;try{const d=await api('poll_command',{pc_slot:s.pcSlot,token:s.token});if(d.command){const result=await execute(d.command).catch(e=>({ok:false,error:String(e?.message||e)}));await api('command_result',{pc_slot:s.pcSlot,token:s.token,command_id:d.command.id,result}).catch(()=>{})}}catch(e){await chrome.storage.local.set({reyInkRelayStatus:{connected:false,error:String(e?.message||e)}})}}
async function startPolling(){if(polling)return;polling=true;while(polling){await poll();await sleep(250)}polling=false}
async function ensureOff(){const u=chrome.runtime.getURL('offscreen.html'),c=await chrome.runtime.getContexts({contextTypes:['OFFSCREEN_DOCUMENT'],documentUrls:[u]});if(c.length)return;if(offscreenCreating){await offscreenCreating;return}offscreenCreating=chrome.offscreen.createDocument({url:'offscreen.html',reasons:['USER_MEDIA'],justification:'Canal remoto Rey Ink.'});try{await offscreenCreating}finally{offscreenCreating=null}}
async function off(m){await ensureOff();return new Promise(r=>chrome.runtime.sendMessage({...m,target:'offscreen'},x=>r(x||{ok:true})))}
async function state(){const t=await tab(),s=await chrome.storage.local.get(['reyInkRemote','reyInkRelayStatus']);return{ok:true,tabId:t?.id||null,url:t?.url||'',title:t?.title||'',remote:s.reyInkRemote||null,relayStatus:s.reyInkRelayStatus||null}}
chrome.runtime.onMessage.addListener((m,s,send)=>{(async()=>{try{switch(m.type){case'GET_STATE':return state();case'CONNECT':return register();case'DISCONNECT':polling=false;await chrome.storage.local.set({reyInkRemote:{enabled:false},reyInkRelayStatus:{connected:false}});try{await off({action:'WEBRTC_STOP'})}catch{}return{ok:true};case'RELOAD':return execute({command:'reload'});case'BACK':return execute({command:'back'});case'FORWARD':return execute({command:'forward'});case'NAVIGATE':return execute({command:'navigate',payload:{url:m.url}});default:return{ok:false,error:'Comando no reconocido'}}}catch(e){return{ok:false,error:String(e?.message||e)}}})().then(send);return true});
chrome.debugger.onEvent.addListener((src,method,p)=>{if(method==='Page.screencastFrame'&&src.tabId){off({action:'FRAME',data:p.data,meta:p.metadata,sessionId:p.sessionId}).catch(()=>{});chrome.debugger.sendCommand({tabId:src.tabId},'Page.screencastFrameAck',{sessionId:p.sessionId}).catch(()=>{})}});
chrome.runtime.onStartup.addListener(()=>{register().catch(()=>{});heartbeat()});chrome.runtime.onInstalled.addListener(()=>{register().catch(()=>{})});setInterval(heartbeat,15000);
