const $=id=>document.getElementById(id);
async function msg(type,data={}){return await new Promise(resolve=>chrome.runtime.sendMessage({type,...data},r=>resolve(r||{ok:false,error:chrome.runtime.lastError?.message||'Error'})))}
function show(id,text,good=true){const e=$(id);if(!e)return;e.textContent=(good?'● ':'⚠ ')+text;e.className='status '+(good?'ok':'err')}
async function state(){return msg('GET_STATE')}
function log(x){const e=$('diag');if(e)e.textContent=new Date().toLocaleTimeString()+'  '+x+'\n'+e.textContent}
async function refreshPCs(){try{const d=await (await fetch('https://rey-ink-browser.vercel.app/api/rey-ink?action=list_devices',{cache:'no-store'})).json(),s=$('pc');if(!s)return;const old=s.value;s.innerHTML='<option value="">Selecciona PC</option>';for(const x of d.devices||[]){const o=document.createElement('option');o.value=String(x.pc_slot);o.textContent='PC '+x.pc_slot+(x.is_online?' · 🟢 en línea':'');s.appendChild(o)}if(old)s.value=old}catch{}}
$('connect').onclick=async()=>{const n=Number($('pc')?.value);if(n<1||n>20){show('relay','Selecciona PC1–PC20.',false);return}try{const tabs=await chrome.tabs.query({active:true,currentWindow:true}),t=tabs.find(x=>x?.id&&/^https?:/i.test(x.url||''));if(!t?.id)throw Error('Abre primero una página web normal en Chrome.');show('relay','Conectando PC'+n+'…');await msg('WEBRTC_STOP').catch(()=>{});if(!(await msg('SET_PC_SLOT',{pcSlot:n})).ok)throw Error('No se pudo seleccionar la PC.');const reg=await msg('REGISTER_REMOTE');if(!reg?.ok)throw Error(reg?.error||'No se pudo registrar la PC.');const host=await msg('WEBRTC_HOST');if(!host?.ok)throw Error(host?.error||'No se pudo preparar el canal remoto.');const video=await msg('START_REMOTE_VIDEO');if(!video?.ok)throw Error(video?.error||'No se pudo iniciar el vídeo remoto.');show('relay','🟢 PC'+n+' conectada · control real activo');log('Conexión lista: CDP + WebRTC.')}catch(e){show('relay',e.message||String(e),false);log('ERROR: '+(e.message||e))}};
$('disconnect').onclick=async()=>{const r=await msg('DISCONNECT_REMOTE');show('relay',r?.ok?'PC desconectada.':r?.error||'Error',!!r?.ok)};
$('check').onclick=async()=>{const r=await state();show('browser',r?.ok?(r.title||'Pestaña activa')+'\n'+(r.url||''):(r.error||'Error'),!!r?.ok)};
$('reload').onclick=async()=>log((await msg('RELOAD')).ok?'Recargar: OK':'Recargar: error');$('back').onclick=async()=>log((await msg('GO_BACK')).ok?'Atrás: OK':'Atrás: error');$('forward').onclick=async()=>log((await msg('GO_FORWARD')).ok?'Adelante: OK':'Adelante: error');$('go').onclick=async()=>log((await msg('NAVIGATE',{url:$('url').value})).ok?'Navegar: OK':'Navegar: error');
$('record').onclick=async()=>{const r=await msg('AUTO_RECORD_START');show('autoStatus',r?.ok?'🔴 Grabando clics reales.':r?.error||'No se pudo iniciar.',!!r?.ok)};$('stopRecord').onclick=async()=>{const r=await msg('AUTO_RECORD_STOP');if(!r?.ok){show('autoStatus',r?.error||'Error',false);return}const s=await state(),count=s?.draft?.length||0;if(!count){show('autoStatus','No se registraron clics.',false);return}const name=prompt('Nombre de la rutina:','Auto clic');if(name===null)return;const saved=await msg('SAVE_AUTO_ROUTINE',{name:name.trim()||'Auto clic'});show('autoStatus',saved?.ok?'Rutina guardada con '+count+' clics.':saved?.error||'Error',!!saved?.ok);refreshRoutines()};$('schedule').onclick=async()=>{const r=await msg('SCHEDULE_AUTO',{index:Number($('routineSelect')?.value||0),minutes:Number($('minutes').value)||16});show('autoStatus',r?.ok?'⏱️ Programa activo cada '+(Number($('minutes').value)||16)+' minutos.':r?.error||'Error',!!r?.ok)};$('stopSchedule').onclick=async()=>show('autoStatus',(await msg('STOP_SCHEDULE')).ok?'Programa detenido.':'Error',true);$('run').onclick=async()=>{const r=await msg('RUN_ROUTINE_NOW',{index:Number($('routineSelect')?.value||0)});show('autoStatus',r?.ok?'Rutina ejecutada.':r?.error||'Error',!!r?.ok)};
async function refreshRoutines(){const r=await state(),box=$('routines');if(!box)return;box.innerHTML='';const list=r?.routines||[];if(!list.length){box.textContent='No hay rutinas guardadas todavía.';return}const sel=document.createElement('select');sel.id='routineSelect';for(const [i,x] of list.entries()){const o=document.createElement('option');o.value=i;o.textContent=(x.name||'Rutina '+(i+1))+' · '+(x.actions?.length||0)+' clics';sel.appendChild(o)}box.appendChild(sel)}$('diagBtn').onclick=async()=>{$('diag').textContent=JSON.stringify(await state(),null,2)};refreshPCs();refreshRoutines();
