const API='https://rey-ink-browser.vercel.app/api/rey-ink';
let rtc=null,dc=null,stream=null;
const ICE={iceServers:[{urls:'stun:stun.l.google.com:19302'},{urls:'stun:stun1.l.google.com:19302'}]};
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function post(action,body){const r=await fetch(API,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action,...body}),cache:'no-store'});const d=await r.json().catch(()=>({error:'Respuesta inválida'}));if(!r.ok||d.ok===false)throw Error(d.error||`HTTP ${r.status}`);return d}
async function cleanup(){try{dc?.close()}catch{}try{rtc?.close()}catch{}try{stream?.getTracks().forEach(t=>t.stop())}catch{}dc=null;rtc=null;stream=null;try{await chrome.runtime.sendMessage({type:'WEBRTC_STATUS',connected:false,state:'closed'})}catch{}}
async function waitIce(){if(!rtc||rtc.iceGatheringState==='complete')return;await new Promise(resolve=>{const f=()=>{if(!rtc||rtc.iceGatheringState==='complete'){rtc?.removeEventListener('icegatheringstatechange',f);resolve()}};rtc.addEventListener('icegatheringstatechange',f);setTimeout(resolve,8000)})}
async function host(streamId,slot,session,token){await cleanup();stream=await navigator.mediaDevices.getUserMedia({audio:false,video:{mandatory:{chromeMediaSource:'tab',chromeMediaSourceId:streamId}}});rtc=new RTCPeerConnection(ICE);stream.getTracks().forEach(t=>rtc.addTrack(t,stream));dc=rtc.createDataChannel('control',{ordered:true});dc.onopen=()=>chrome.runtime.sendMessage({type:'WEBRTC_STATUS',connected:true,state:'connected'}).catch(()=>{});dc.onclose=()=>chrome.runtime.sendMessage({type:'WEBRTC_STATUS',connected:false,state:'datachannel_closed'}).catch(()=>{});dc.onmessage=e=>{try{chrome.runtime.sendMessage({target:'background',...JSON.parse(e.data)})}catch{}};rtc.onconnectionstatechange=()=>{const s=rtc?.connectionState;chrome.runtime.sendMessage({type:'WEBRTC_STATUS',connected:s==='connected',state:s}).catch(()=>{});if(['failed','closed','disconnected'].includes(s))setTimeout(()=>cleanup(),500)};const offer=await rtc.createOffer();await rtc.setLocalDescription(offer);await waitIce();await post('webrtc_offer',{pc_slot:slot,session,token,offer:rtc.localDescription});for(let i=0;i<120;i++){const r=await fetch(API+'?action=webrtc_answer&pc_slot='+encodeURIComponent(slot)+'&session='+encodeURIComponent(session),{cache:'no-store'});const d=await r.json().catch(()=>({}));if(d.answer){await rtc.setRemoteDescription(d.answer);return{ok:true}}await sleep(500)}await cleanup();throw Error('El teléfono no respondió al enlace WebRTC.');}
chrome.runtime.onMessage.addListener((m,s,r)=>{if(m?.target!=='offscreen')return;if(m.action==='WEBRTC_STOP'){cleanup().then(()=>r({ok:true}));return true}if(m.action==='WEBRTC_HOST'){(async()=>{const x=await chrome.storage.local.get('reyInkRemote'),d=x.reyInkRemote||{};if(!d.session||!d.token)throw Error('Sesión Rey Ink no disponible.');return host(m.streamId,d.pcSlot,d.session,d.token)})().then(r).catch(e=>r({ok:false,error:String(e?.message||e)}));return true}return false});
