const API='https://rey-ink-browser.vercel.app/api/rey-ink';
let rtc=null,dc=null,stream=null,canvas=null,ctx=null;
const ICE={iceServers:[{urls:'stun:stun.l.google.com:19302'},{urls:'stun:stun1.l.google.com:19302'}]};
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function post(action,body){const r=await fetch(API,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action,...body}),cache:'no-store'});const d=await r.json().catch(()=>({}));if(!r.ok||d.ok===false)throw Error(d.error||`HTTP ${r.status}`);return d}
async function cleanup(){try{dc?.close()}catch{}try{rtc?.close()}catch{}try{stream?.getTracks().forEach(t=>t.stop())}catch{}rtc=null;dc=null;stream=null;canvas=null;ctx=null;try{await chrome.runtime.sendMessage({type:'WEBRTC_STATUS',connected:false,state:'closed'})}catch{}}
async function ice(){if(!rtc||rtc.iceGatheringState==='complete')return;await new Promise(r=>{const f=()=>{if(!rtc||rtc.iceGatheringState==='complete'){rtc?.removeEventListener('icegatheringstatechange',f);r()}};rtc.addEventListener('icegatheringstatechange',f);setTimeout(r,8000)})}
async function host(){await cleanup();canvas=document.createElement('canvas');canvas.width=1280;canvas.height=720;canvas.style.display='none';document.body.appendChild(canvas);ctx=canvas.getContext('2d',{alpha:false});ctx.fillStyle='#000';ctx.fillRect(0,0,canvas.width,canvas.height);stream=canvas.captureStream(15);rtc=new RTCPeerConnection(ICE);stream.getTracks().forEach(t=>rtc.addTrack(t,stream));dc=rtc.createDataChannel('control',{ordered:true});dc.onopen=()=>chrome.runtime.sendMessage({type:'WEBRTC_STATUS',connected:true,state:'connected'}).catch(()=>{});dc.onclose=()=>chrome.runtime.sendMessage({type:'WEBRTC_STATUS',connected:false,state:'datachannel_closed'}).catch(()=>{});rtc.onconnectionstatechange=()=>{const s=rtc?.connectionState;chrome.runtime.sendMessage({type:'WEBRTC_STATUS',connected:s==='connected',state:s}).catch(()=>{})};const offer=await rtc.createOffer();await rtc.setLocalDescription(offer);await ice();const x=await chrome.storage.local.get('reyInkRemote'),d=x.reyInkRemote||{};if(!d.session||!d.token)throw Error('Sesión Rey Ink no disponible.');await post('webrtc_offer',{pc_slot:d.pcSlot,session:d.session,token:d.token,offer:rtc.localDescription});for(let i=0;i<120;i++){const r=await fetch(API+'?action=webrtc_answer&pc_slot='+encodeURIComponent(d.pcSlot)+'&session='+encodeURIComponent(d.session),{cache:'no-store'}),a=await r.json().catch(()=>({}));if(a.answer){await rtc.setRemoteDescription(a.answer);return{ok:true}}await sleep(500)}throw Error('El teléfono no respondió al enlace WebRTC.')}
async function frame(data){if(!ctx)return;try{const raw=atob(data),u=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)u[i]=raw.charCodeAt(i);const b=new Blob([u],{type:'image/jpeg'}),img=await createImageBitmap(b);const scale=Math.min(canvas.width/img.width,canvas.height/img.height),w=img.width*scale,h=img.height*scale;ctx.fillStyle='#000';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(img,(canvas.width-w)/2,(canvas.height-h)/2,w,h);img.close()}catch{}}
chrome.runtime.onMessage.addListener((m,s,r)=>{if(m?.target!=='offscreen')return;if(m.action==='WEBRTC_STOP'){cleanup().then(()=>r({ok:true}));return true}if(m.action==='WEBRTC_HOST'){host().then(r).catch(e=>r({ok:false,error:String(e?.message||e)}));return true}if(m.action==='FRAME'){frame(m.data).then(()=>r({ok:true}));return true}return false});
