(function(){'use strict';
const q=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
let timer=0,loading=false,all=[],clients=[],devices=[];
const api=async b=>{for(let i=0;i<30;i++){if(window.__RI_ADMIN?.api)return window.__RI_ADMIN.api(b);await new Promise(r=>setTimeout(r,200))}throw Error('Control Center no está listo.')};
const detail=x=>x?.details&&typeof x.details==='object'?x.details:{};
function clientName(x){const d=detail(x),id=x?.client_id||d.client_id||x?.metadata?.client_id;return clients.find(c=>String(c.id)===String(id))?.name||x?.client_name||d.client_name||x?.label||d.label||'—'}
function deviceName(x){const d=detail(x),id=x?.device_id||d.device_id||x?.metadata?.device_id;return devices.find(v=>String(v.id)===String(id))?.name||devices.find(v=>String(v.id)===String(id))?.metadata?.display_name||'—'}
function actionName(a){return ({create_link:'Link generado',delete_link:'Link revocado',create_client:'Cliente creado',update_client:'Cliente actualizado',delete_client:'Cliente eliminado',rename_device:'Navegador renombrado',assign_device:'Navegador asignado',create_license:'Licencia creada',activate_license:'Licencia activada',delete_license:'Licencia eliminada',bot_command:'Comando del bot',claim_pairing:'Navegador emparejado'})[a]||String(a||'Actividad')}
function kind(a){if(/link/i.test(a))return'LINK';if(/client/i.test(a))return'CLIENTE';if(/license/i.test(a))return'LICENCIA';if(/device|pair/i.test(a))return'NAVEGADOR';if(/bot/i.test(a))return'BOT';return'SISTEMA'}
function date(x){const v=x?.created_at||x?.timestamp||x?.createdAt;return v?new Date(v):null}
function row(x){const a=String(x?.action||'').toLowerCase(),d=detail(x),dt=date(x),cn=clientName(x),dn=deviceName(x);return '<div class="riActRow" data-search="'+esc([actionName(a),kind(a),cn,dn,x?.target||'',JSON.stringify(d)].join(' '))+'"><div class="riActIcon">'+(kind(a)==='LINK'?'↗':kind(a)==='CLIENTE'?'♙':kind(a)==='NAVEGADOR'?'▣':kind(a)==='LICENCIA'?'◇':kind(a)==='BOT'?'⚡':'◷')+'</div><div class="riActMain"><b>'+esc(actionName(a))+'</b><span>'+esc(cn)+(dn!=='—'?' · '+esc(dn):'')+'</span><small>'+esc(d?.label||x?.label||x?.target||'')+'</small></div><div class="riActRight"><em>'+kind(a)+'</em><time>'+(dt&&!isNaN(dt)?esc(dt.toLocaleString('es-DO',{dateStyle:'short',timeStyle:'medium'})):'—')+'</time></div></div>'}
function render(){const s=q('#riActivityCenter');if(!s)return;const text=(q('#riActSearch')?.value||'').trim().toLowerCase(),type=q('#riActType')?.value||'ALL',client=q('#riActClient')?.value||'ALL',device=q('#riActDevice')?.value||'ALL';let list=all.filter(x=>{const a=String(x?.action||'').toLowerCase(),k=kind(a),d=detail(x),cid=String(x?.client_id||d.client_id||x?.metadata?.client_id||''),did=String(x?.device_id||d.device_id||x?.metadata?.device_id||'');return(!text||String([actionName(a),k,clientName(x),deviceName(x),x?.target||'',JSON.stringify(d)].join(' ')).toLowerCase().includes(text))&&(type==='ALL'||k===type)&&(client==='ALL'||cid===client)&&(device==='ALL'||did===device)});q('#riActCount').textContent=list.length+' eventos';q('#riActList').innerHTML=list.length?list.map(row).join(''):'<div class="riActEmpty">No hay actividad que coincida con los filtros.</div>'}
function controls(){const s=q('#riActivityCenter');if(!s||s.dataset.ready)return;s.dataset.ready='1';s.innerHTML='<div class="riActHead"><div><h2>Actividad e historial</h2><p>Registro de operaciones del Control Center</p></div><button class="btn" id="riActRefresh">↻ Actualizar</button></div><div class="riActStats"><div><b id="riActTotal">0</b><span>Total cargado</span></div><div><b id="riActLinks">0</b><span>Movimientos de links</span></div><div><b id="riActClients">0</b><span>Movimientos de clientes</span></div><div><b id="riActCount">0</b><span>Resultado actual</span></div></div><div class="riActFilters"><input id="riActSearch" class="input" placeholder="Buscar cliente, navegador, acción o detalle…"><select id="riActType" class="select"><option value="ALL">Todas las categorías</option><option>LINK</option><option>CLIENTE</option><option>NAVEGADOR</option><option>LICENCIA</option><option>BOT</option><option>SISTEMA</option></select><select id="riActClient" class="select"><option value="ALL">Todos los clientes</option></select><select id="riActDevice" class="select"><option value="ALL">Todos los navegadores</option></select><button class="btn mini" id="riActClear">Limpiar filtros</button></div><div id="riActList" class="riActList"></div>';q('#riActRefresh').onclick=load;q('#riActClear').onclick=()=>{['riActSearch','riActType','riActClient','riActDevice'].forEach(id=>{const e=q('#'+id);if(e)e.value=id==='riActType'||id==='riActClient'||id==='riActDevice'?'ALL':''});render()};['riActSearch','riActType','riActClient','riActDevice'].forEach(id=>q('#'+id)?.addEventListener(id==='riActSearch'?'input':'change',render))}
function selects(){const c=q('#riActClient'),d=q('#riActDevice');if(c){const v=c.value;c.innerHTML='<option value="ALL">Todos los clientes</option>'+clients.map(x=>'<option value="'+esc(x.id)+'">'+esc(x.name||'Cliente')+'</option>').join('');c.value=[...c.options].some(o=>o.value===v)?v:'ALL'}if(d){const v=d.value;d.innerHTML='<option value="ALL">Todos los navegadores</option>'+devices.map(x=>'<option value="'+esc(x.id)+'">'+esc(x.name||x.metadata?.display_name||'Navegador')+'</option>').join('');d.value=[...d.options].some(o=>o.value===v)?v:'ALL'}}
async function load(){if(loading)return;loading=true;try{const[r,h]=await Promise.all([api({action:'getData'}),api({action:'history'})]);const x=r?.data||r||{};clients=Array.isArray(x.clients)?x.clients:[];devices=Array.isArray(x.devices)?x.devices:[];all=Array.isArray(h?.history)?h.history:Array.isArray(h?.data)?h.data:[];selects();q('#riActTotal').textContent=all.length;q('#riActLinks').textContent=all.filter(x=>/link/i.test(x?.action||'')).length;q('#riActClients').textContent=all.filter(x=>/client/i.test(x?.action||'')).length;render()}catch(e){const l=q('#riActList');if(l)l.innerHTML='<div class="riActEmpty">'+esc(e.message)+'</div>'}finally{loading=false}}
function boot(){const sec=q('#history');if(!sec)return;let s=q('#riActivityCenter');if(!s){s=document.createElement('div');s.id='riActivityCenter';sec.append(s)}controls();load();clearInterval(timer);timer=setInterval(()=>{if(sec.classList.contains('active'))load()},15000)}
new MutationObserver(()=>{if(q('#history')?.classList.contains('active'))setTimeout(boot,50)}).observe(document.documentElement,{childList:true,subtree:true});setTimeout(boot,900);document.addEventListener('click',e=>{if(e.target.closest('.tab[data-tab="history"]'))setTimeout(boot,80)});
})();