(function(){'use strict';
const qs=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
let links=[], history=[], clients=[], devices=[], filterClient='';
async function call(body){for(let i=0;i<30;i++){if(window.__RI_ADMIN?.api)return window.__RI_ADMIN.api(body);await new Promise(r=>setTimeout(r,250));}throw new Error('Control Center no está listo.');}
function normalizeData(x){const d=x?.data||x?.result||x||{};return{links:Array.isArray(d.links)?d.links:[],clients:Array.isArray(d.clients)?d.clients:[],devices:Array.isArray(d.devices)?d.devices:[]};}
async function load(){try{const [dr,hr]=await Promise.all([call({action:'getData'}),call({action:'history'})]);const d=normalizeData(dr);links=d.links;clients=d.clients;devices=d.devices;history=Array.isArray(hr?.history)?hr.history:(Array.isArray(hr?.data)?hr.data:[]);render()}catch(e){render(e.message)}}
function render(err=''){const sec=qs('#links');if(!sec)return;let box=qs('#riLinkManager');if(!box){box=document.createElement('div');box.id='riLinkManager';sec.prepend(box)}const active=links.filter(x=>x.active!==false);const shown=filterClient?links.filter(x=>String(x.client_id||'')===filterClient):links;box.innerHTML=`<div class="riLinkPanel"><div class="riLinkHead"><div><div class="riLinkTitle">Administración de links</div><div class="riLinkSub">Genera, consulta, copia y revoca los links individuales de tus clientes.</div></div><div class="riLinkCount"><b>${active.length}</b> activos</div></div>${err?`<div class="riLinkErr">${esc(err)}</div>`:''}<div class="riLinkTools"><select id="riLinkClient"><option value="">Todos los clientes</option>${clients.map(c=>`<option value="${esc(c.id)}" ${String(c.id)===filterClient?'selected':''}>${esc(c.name||'Cliente')}</option>`).join('')}</select><select id="riLinkDevice"><option value="">Selecciona navegador</option>${devices.map(d=>`<option value="${esc(d.id)}">${esc(d.name||d.metadata?.display_name||'Navegador')} — ${d.is_online?'ONLINE':'offline'}</option>`).join('')}</select><button class="btn" data-ri="generate">＋ Generar link</button><button class="btn" data-ri="refresh">↻ Actualizar</button></div><div class="riLinkTableWrap"><table class="table"><thead><tr><th>Cliente</th><th>Link</th><th>Estado</th><th>Creado</th><th>Acciones</th></tr></thead><tbody>${shown.length?shown.map(l=>{const name=l.label||'Cliente';const url=l.url||l.link||l.href||((location.origin||'')+'/?d='+encodeURIComponent(l.token||''));const id=l.id||'';const isActive=l.active!==false;return`<tr><td><b>${esc(name)}</b></td><td><div class="riLinkUrl">${esc(url)}</div></td><td>${isActive?'<span class="green">● Activo</span>':'<span class="red">● Revocado</span>'}</td><td>${l.created_at?esc(new Date(l.created_at).toLocaleString()):'—'}</td><td><button class="btn mini" data-ri="copy" data-url="${esc(url)}">Copiar</button> ${isActive&&id?`<button class="btn mini danger" data-ri="revoke" data-id="${esc(id)}">Revocar</button>`:''}</td></tr>`}).join(''):`<tr><td colspan="5" class="empty">No hay links registrados.</td></tr>`}</tbody></table></div><div class="riActivity"><div class="riLinkTitle">Actividad de links</div><div class="riLinkSub">Historial relacionado con generación y revocación.</div><div class="riEvents">${renderHistory()}</div></div></div>`}
function renderHistory(){const h=history.filter(x=>!filterClient||String(x.client_id||x.details?.client_id||x.metadata?.client_id||'')===filterClient&&(x.action==='create_link'||x.action==='delete_link'));if(!h.length)return'<div class="empty">No hay actividad para este cliente.</div>';return h.slice(0,100).map(x=>`<div class="riEvent"><div><b>${esc(x.action==='create_link'?'Link generado':x.action==='delete_link'?'Link revocado':x.action||'Actividad')}</b> <span>${esc(x.details?.label||x.label||x.entity_id||'')}</span></div><small>${x.created_at?esc(new Date(x.created_at).toLocaleString()):''}</small></div>`).join('')}
document.addEventListener('change',e=>{if(e.target.id==='riLinkClient'){filterClient=e.target.value||'';render()}});
document.addEventListener('click',async e=>{const b=e.target.closest('[data-ri]');if(!b)return;if(b.dataset.ri==='refresh'){load();return}if(b.dataset.ri==='copy'){try{await navigator.clipboard.writeText(b.dataset.url||'');b.textContent='Copiado ✓';setTimeout(()=>b.textContent='Copiar',1200)}catch(_){alert('No se pudo copiar el link.')}return}if(b.dataset.ri==='generate'){const clientId=qs('#riLinkClient')?.value||'';const deviceId=qs('#riLinkDevice')?.value||'';if(!clientId)return alert('Selecciona un cliente.');if(!deviceId)return alert('Selecciona un navegador.');const c=clients.find(x=>String(x.id)===clientId),d=devices.find(x=>String(x.id)===deviceId);const label=c?.name||'Cliente';b.disabled=true;try{const r=await call({action:'create_link',client_id:clientId,device_id:deviceId,label,base_url:location.origin});if(!r?.ok)throw new Error(r?.error||'No se pudo generar el link.');await load();if(window.__RI_ADMIN?.refresh)await window.__RI_ADMIN.refresh();}catch(err){alert(err.message||'No se pudo generar el link.')}finally{b.disabled=false}return}if(b.dataset.ri==='revoke'){if(!confirm('¿Revocar este link? El link dejará de estar activo.'))return;b.disabled=true;try{await call({action:'delete_link',link_id:b.dataset.id});await load();if(window.__RI_ADMIN?.refresh)await window.__RI_ADMIN.refresh()}catch(err){alert(err.message||'No se pudo revocar el link.');b.disabled=false}}});
const boot=()=>{if(qs('#links'))load()};new MutationObserver(boot).observe(document.documentElement,{childList:true,subtree:true});setTimeout(boot,800);
})();