(function(){'use strict';const q=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function counts(){const n=id=>q(id)?.textContent||'0';const rows=[...document.querySelectorAll('#linksTable tbody tr')];return{clients:n('#clientsN'),browsers:n('#npcs'),online:n('#online'),licenses:n('#active'),links:rows.length&&!/No hay links/i.test(rows[0]?.textContent||'')?String(rows.length):'0'}}
function tab(name){q('.tab[data-tab="'+name+'"]')?.click()}
function header(){const h=q('.head');if(!h||h.dataset.refui)return;h.dataset.refui='1';const r=q('#refresh');h.innerHTML='<div id="riWelcome"><div><div class="riWelcomeTitle">Bienvenido, Administrador <span class="riAdmin">SUPER ADMIN</span></div><div class="riWelcomeSub">Centro de control y monitoreo del sistema Rey Ink</div></div></div><div class="riHeaderMeta"><div class="riMeta"><div class="riMetaLabel">Fecha y Hora</div><div class="riMetaValue" id="riClock">—</div></div><div class="riMeta"><div class="riMetaLabel">Conexión del Sistema</div><div class="riMetaValue riOnline">● ONLINE</div></div></div>';if(r)h.append(r);const tick=()=>{const e=q('#riClock');if(e)e.textContent=new Date().toLocaleString('es-DO',{dateStyle:'short',timeStyle:'medium'})};tick();setInterval(tick,1000)}
function sidebar(){const t=q('.tabs');if(!t||q('#riSidebarFooter'))return;const f=document.createElement('div');f.id='riSidebarFooter';f.innerHTML='<div class="riSideBox"><div class="riSideLabel">Sistema operativo</div><div class="riSideMain">Control Center</div><div class="riSideOnline">● ONLINE</div></div><div class="riSideBox"><div class="riSideUser"><div class="riSideAvatar">♛</div><div><div class="riSideMain">Administrador</div><div class="riSideLabel">Super Admin</div></div></div></div>';t.append(f)}
function dashboard(){const home=q('#home');if(!home)return;let d=q('#riDash');if(!d){d=document.createElement('div');d.id='riDash';home.append(d)}const c=counts(),browsers=[...document.querySelectorAll('#pcsTable tbody tr')],active=browsers.filter(x=>/ACTIVO/i.test(x.textContent||'')).length,online=browsers.filter(x=>/En línea/i.test(x.textContent||'')).length,clients=[...document.querySelectorAll('#clientsTable tbody tr')].slice(0,4),lic=[...document.querySelectorAll('#licensesTable tbody tr')].slice(0,4),links=[...document.querySelectorAll('#linksTable tbody tr')].slice(0,4),hist=[...document.querySelectorAll('#historyList .event')].slice(0,4);d.innerHTML='';
const panel=(cls,title,body,link='')=>'<div class="riPanel '+cls+'"><div class="riPanelHead"><span class="riPanelTitle">'+title+'</span><span class="riPanelLink">'+link+'</span></div>'+body+'</div>';
d.innerHTML=panel('riBot','ESTADO DEL BOT','<div class="riBotBody"><div class="riCore"><div class="riBotIcon">🤖</div></div><div><div class="riBotState">'+(active?'BOT ACTIVO':'BOT DESACTIVADO')+'</div><div class="riBotText">'+(active?active+' bot(s) en ejecución':'El bot no está en ejecución')+'</div><div class="riNext"><small>PRÓXIMA ACCIÓN</small><b>'+(online?'Estado sincronizado con los navegadores conectados':'No hay tareas programadas')+'</b></div></div></div><div class="riControls"><button class="btn riStart" id="riStartBtn">▶ Iniciar Bot</button><button class="btn riPause" id="riPauseBtn">Ⅱ Pausar</button><button class="btn riStop" id="riStopBtn">■ Detener</button></div>')+
panel('riBrowsers','NAVEGADORES CONECTADOS','<div class="riRadar"></div><div class="riEmpty"><b>'+(online?online+' CONECTADOS':'SIN CONEXIONES')+'</b><div>'+(online?'Navegadores activos en este momento':'No hay navegadores conectados')+'</div><button class="btn" id="riBrowsersBtn">Ver Navegadores</button></div>','Ver todos ›')+
panel('riLicenses','LICENCIAS ACTIVAS','<div class="riEmptyRow"><div class="riOrb">▣</div><div class="riEmptyText"><b>'+(lic.length?lic.length+' licencia(s) activas':'No hay licencias activas')+'</b><div>'+(lic.length?'Licencias registradas en el sistema':'Aún no se han creado licencias')+'</div><button class="btn" id="riLicBtn">Gestionar Licencias</button></div></div>','Ver todas ›')+
panel('riActivity','ACTIVIDAD RECIENTE','<div class="riList">'+(hist.length?hist.map(x=>'<div class="riRow"><div class="riRowMain"><b>'+esc(x.querySelector('b')?.textContent||'Actividad')+'</b><small>'+esc(x.querySelector('small')?.textContent||'')+'</small></div><span class="riPill">LOG</span></div>').join(''):'<div class="riEmptyRow"><div class="riOrb">ϟ</div><div class="riEmptyText"><b>No hay actividad registrada</b><div>La actividad del sistema aparecerá aquí</div></div></div>')+'</div>','Ver todo ›')+
panel('riLinks','LINKS GENERADOS','<div class="riEmptyRow"><div class="riOrb">↗</div><div class="riEmptyText"><b>'+(links.length?links.length+' link(s) generados':'No hay links generados')+'</b><div>'+(links.length?'Links disponibles en el sistema':'Aún no se han generado links')+'</div><button class="btn" id="riLinkBtn">Generar Link</button></div></div>','Ver todos ›')+
panel('riClients','CLIENTES RECIENTES','<div class="riClientList">'+(clients.length?clients.map(x=>'<div class="riClient"><b>'+esc(x.querySelector('td')?.textContent?.trim()||'Cliente')+'</b><small>Cliente registrado</small></div>').join(''):'<div class="riEmptyRow" style="grid-column:1/-1"><div class="riOrb">♙</div><div class="riEmptyText"><b>No hay clientes registrados</b><div>Comienza agregando tu primer cliente al sistema</div><button class="btn" id="riClientBtn">Gestionar Clientes</button></div></div>')+'</div>','Ver todos ›')+
panel('riStats','ESTADÍSTICAS DEL SISTEMA','<div class="riStatGrid"><div class="riStat"><span>Uptime del Sistema</span><strong class="riGreen">Online</strong></div><div class="riStat"><span>Clientes</span><strong>'+esc(c.clients)+'</strong></div><div class="riStat"><span>Emparejamientos</span><strong>'+esc(c.browsers)+'</strong></div><div class="riStat"><span>Licencias activas</span><strong>'+esc(c.licenses)+'</strong></div></div>')+
panel('riQuick','ACCESOS RÁPIDOS','<div class="riQuickGrid"><button class="riQuickBtn" id="riNewClient"><span>♙</span>Nuevo Cliente</button><button class="riQuickBtn" id="riNewLink"><span>↗</span>Generar Link</button><button class="riQuickBtn" id="riNewLicense"><span>▣</span>Nueva Licencia</button><button class="riQuickBtn" id="riLogs"><span>▤</span>Ver Logs</button><button class="riQuickBtn" id="riPair"><span>⌘</span>Emparejar</button><button class="riQuickBtn" id="riConfig"><span>⚙</span>Configuración</button></div>','›');
[['#riBrowsersBtn','browsers'],['#riLicBtn','licenses'],['#riViewLic','licenses'],['#riLinkBtn','links'],['#riClientBtn','clients'],['#riNewClient','clients'],['#riNewLink','links'],['#riNewLicense','licenses'],['#riLogs','history'],['#riPair','browsers'],['#riBrowsers','browsers']].forEach(([id,n])=>{const e=q(id);if(e)e.onclick=()=>tab(n)});q('#riViewHist')?.addEventListener('click',()=>tab('history'));q('#riViewClients')?.addEventListener('click',()=>tab('clients'));
const s=q('#pcsTable [data-act="bot-start"]'),st=q('#pcsTable [data-act="bot-stop"]),ss=q('#pcsTable [data-act="bot-state"]');if(s)q('#riStartBtn').onclick=()=>s.click();if(st)q('#riStopBtn').onclick=()=>st.click();if(ss)q('#riPauseBtn').onclick=()=>ss.click();}
function addMetric(){const g=q('#home>.grid');if(!g||q('#riLinksMetric'))return;const e=document.createElement('div');e.id='riLinksMetric';e.innerHTML='<span class="riMetricAccent"></span><div class="riMetricNum" id="riLinksNum">0</div><div class="riMetricLabel">Links</div><div class="riMetricSub">Generados</div>';g.append(e)}
function boot(){header();sidebar();const g=q('#home>.grid'),st=q('#status');if(g)g.style.display='grid';if(st)st.style.display='none';addMetric();dashboard();const watch=['#clientsN','#npcs','#online','#active','#clientsTable','#pcsTable','#licensesTable','#linksTable','#historyList'];const mo=new MutationObserver(()=>{addMetric();const c=counts();if(q('#riLinksNum'))q('#riLinksNum').textContent=c.links;dashboard()});watch.forEach(x=>{const e=q(x);if(e)mo.observe(e,{childList:true,subtree:true,characterData:true})});setInterval(()=>{addMetric();const c=counts();if(q('#riLinksNum'))q('#riLinksNum').textContent=c.links;dashboard()},3000)}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot()})();